version: '3'

services:
  cuentas-ms:
    build: 
      context: ./cuentas-ms
      dockerfile: dockerfile.prod
    image: cuentas-ms-prod
    ports:
      - ${CUENTAS_MS_PORT}:${CUENTAS_MS_PORT}
    environment:
      - PORT=${CUENTAS_MS_PORT}
      - DB_HOST=${CUENTAS_DB_HOST}
      - DB_PORT=${CUENTAS_DB_PORT}
      - DB_NAME=${CUENTAS_DB_NAME}
      - DB_USERNAME=${CUENTAS_DB_USER}
      - DB_PASSWORD=${CUENTAS_DB_PASS}

  compras-ms:
    build:
      context: ./compras-ms
      dockerfile: dockerfile.prod
    image: products-ms-prod
    ports:
      - ${COMPRAS_MS_PORT}:${COMPRAS_MS_PORT}
    environment:
      - PORT=${COMPRAS_MS_PORT}
      - DB_HOST=${COMPRAS_DB_HOST}
      - DB_PORT=${COMPRAS_DB_PORT}
      - DB_NAME=${COMPRAS_DB_NAME}
      - DB_USERNAME=${COMPRAS_DB_USER}
      - DB_PASSWORD=${COMPRAS_DB_PASS}
  
  transacciones-ms:
    build:
      context: ./transacciones-ms
      dockerfile: dockerfile.prod
    image: orders-ms-prod
    ports:
      - ${TRANSAC_MS_PORT}:${TRANSAC_MS_PORT}
    environment:
      - PORT=${TRANSAC_MS_PORT}
      - DB_HOST=${TRANSAC_DB_HOST}
      - DB_PORT=${TRANSAC_DB_PORT}
      - DB_NAME=${TRANSAC_DB_NAME}
      - DB_USERNAME=${TRANSAC_DB_USER}
      - DB_PASSWORD=${TRANSAC_DB_PASS}